// The toolbar icon carries the on/off state: the normal mark while converting,
// the inverted one (a solid disc with the mark knocked out) while off. Artwork
// is generated by build/gen-icons.js.
//
// Shared rather than living in the service worker alone, because an MV3 worker
// is only alive when an event is being delivered. Relying on it to observe
// storage.onChanged is enough in principle but leaves the visible state one
// wake-up away from the click that caused it, and a worker that fails to start
// leaves the icon permanently stale. The popup — which is definitely running at
// the moment the user flips the switch — paints too, so the feedback is
// immediate and independent of the worker's lifecycle.

import { browser } from './browser.js';

// setIcon resolves a RELATIVE path against the calling context's document URL,
// not the extension root — so a bare 'icons/16-off.png' becomes
// src/popup/icons/16-off.png from the popup and src/background/icons/… from the
// service worker, and Chrome reports "Could not load action icon". Every path
// therefore goes through runtime.getURL, which is unambiguous from any caller.
const at = (file) => browser.runtime.getURL(`icons/${file}`);
const ON = { 16: at('16.png'), 48: at('48.png'), 128: at('128.png') };
const OFF = { 16: at('16-off.png'), 48: at('48-off.png'), 128: at('128-off.png') };

/**
 * Point the toolbar action at the artwork matching `enabled`.
 *
 * Failures are logged, not swallowed: setIcon rejects on a path it cannot load
 * (a missing file, or one absent from the Firefox build's copy list) and a
 * silent catch there makes a stale icon impossible to diagnose.
 *
 * @param {boolean} enabled
 */
export async function paintActionIcon(enabled) {
  const action = browser.action ?? browser.browserAction; // MV2 Firefox fallback
  if (!action?.setIcon) return;
  try {
    await action.setIcon({ path: enabled ? ON : OFF });
    await action.setTitle?.({ title: enabled ? 'Euspell — converting pages' : 'Euspell — off' });
  } catch (err) {
    console.warn('Euspell: could not set the toolbar icon.', err);
  }
}

/** Read the setting and paint. Used wherever the state may have drifted. */
export async function refreshActionIcon() {
  const { enabled = true } = await browser.storage.sync.get('enabled');
  await paintActionIcon(enabled);
}
