// Auto-generated by build/gen-popup-encodings.mjs — do not edit.
// Source: data/euspell_encoding.csv (34 codes). Descriptions are
// verbatim, so what the tooltip shows is what the table says.
//
// Keyed by the numeric encoding, because that is what a lexicon entry carries:
// compile-lexicon.js parses "012" to 12. Use pad() to get the printed form back.

/** @type {Map<number, string>} */
export const descriptions = new Map([
  [0, "unchanged common word"],
  [11, "unambiguous VVZ ending -s → -z"],
  [12, "NN2|VVZ -s ending disambiguated"],
  [21, "JJ|VVD|VVN ending -ed → -d when warranted"],
  [22, "JJ|VVD|VVN ending disambiguated e.g. blessd/blessed"],
  [41, "doubling consonant before ending"],
  [101, "stem change"],
  [102, "stem disambiguated: ending in -ate"],
  [103, "stem disambiguated three ways"],
  [111, "stem change + unambiguous VVZ ending -s → -z"],
  [112, "stem change + NN2|VVZ ending: disambiguated"],
  [113, "stem change + NN2|VVZ ending: disambiguated three ways"],
  [114, "stem change + NN2|VVZ ending: disambiguated four ways"],
  [121, "stem change + JJ|VVD|VVN ending -ed → -d when warranted"],
  [123, "stem change + JJ|VVD|VVN ending: disambiguated three ways"],
  [131, "stem change: undoubling consonant before ending"],
  [152, "stem disambiguated: not ending in -ate"],
  [202, "stem change – semantic disambiguation needed"],
  [500, "unchanged rare or archaic word"],
  [501, "stem change – rare or archaic word"],
  [511, "VVZ ending -s → -z – rare or archaic word"],
  [521, "JJ|VVD|VVN ending -ed → -d when warranted – rare or archaic word"],
  [601, "merges with existing word (mostly British → American)"],
  [631, "merges with existing word: undoubling consonant before ending"],
  [641, "merges with existing word: doubling consonant before ending"],
  [700, "unchanged word – French pronunciation"],
  [701, "stem change – French pronunciation"],
  [702, "NN1|NN2 disambiguation – French pronunciation"],
  [711, "VVZ ending -s → -z – French pronunciation"],
  [721, "JJ|VVD|VVN ending -ed → -d when warranted – French pronunciation"],
  [800, "unchanged word – Scottish pronunciation"],
  [811, "VVZ ending ending -s → -z – Scottish pronunciation"],
  [821, "VVD|VVN ending -ed → -d when warranted – Scottish pronunciation"],
  [900, "abbreviation"],
]);

/**
 * The three-digit printed form of a numeric encoding: 12 -> "012".
 * @param {number} encoding
 * @returns {string}
 */
export function pad(encoding) {
  return String(encoding).padStart(3, '0');
}
