"""euspell conversion engine — a faithful Python port of the JavaScript engine
(src/content/converter.js, tagger.js, context.js + src/disambig/pos.js and the
NN2|VVZ SVM). It converts traditional English to euspell reformed spelling,
using the surrounding sentence for the context-dependent diatones.

Data is loaded from the sibling data/ directory (generated by build/gen-lo.js):
lexicon.csv, abbreviations.csv, contractions.csv, and vvz_svm.tsv.

What is and isn't ported, vs the JS engine:
  * Ported exactly: the lexical PoS tagger, the tokenizer (incl. genitive/clitic
    'splitting and contraction pseudo-tokens), the context window with sentence
    breaks, the NN2|VVZ linear SVM, and the POS predicates is_verbal_s,
    is_plural_noun, is_verb_VV0 with converter.route()'s dispatch.
  * Not ported (v1): the ~70 per-word *semantic* rules (read/bow/tear/wind/…)
    and multi-word phrase collapsing. For a word that would need a semantic
    rule, route() returns the lexicon's default index; callers that can show
    choices (the proofreader) instead offer all spellings via word_candidates().
"""

import csv
import os
import re

_DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

# --- data structures --------------------------------------------------------
# Each lexicon/abbreviation/contraction entry: {'pos': [str], 'encoding': int,
# 'spellings': [str]}. `pos` is the pipe-split candidate-tag list exactly as the
# JS entry.pos; for a contraction a position element may itself be a
# space-separated CLAWS7 sequence (e.g. 'PN1 GE').

_LEXICON = {}
_ABBR = {}
_CONTRACTIONS = {}   # keyed by apostrophe-normalized lowercase surface form
_SVM = {}            # feature key -> weight
_REVERSE = {}        # euspell reformed form -> traditional word (for revert)

# Words carrying a disambiguation encoding that are nonetheless left exactly as
# written (KEEP_UNCHANGED in converter.js).
_KEEP_UNCHANGED = {"bach", "chis", "ravined"}

# POS heteronyms that take the VERB reading when the context vote is exactly
# zero, instead of the global noun-first default — mirrors VV0_VERB_DEFAULT in
# src/disambig/vv0-prior.js, which build/gen-vv0-prior.mjs learns from the
# CLAWS corpus. Keep in step with that generated file.
_VV0_VERB_DEFAULT = {"bear", "live", "mow", "refuse", "reuse"}

# The ~70 surface words whose multi-spelling choice is decided by a semantic
# (pronunciation) rule in the JS engine. Not ported in v1: route() defaults
# them, and the proofreader offers their spellings as choices.
_SEMANTIC_WORDS = {
    "barred", "bass", "beloved", "blessed", "bow", "bowed", "bowing",
    "bowman", "bowings", "bowmen", "bows", "chi", "cleanly", "close", "closer",
    "conch", "copyread", "does", "dogged", "dove", "foreread", "gets", "jagged",
    "lead", "leads", "learned", "longed", "looks", "makes", "means", "minute",
    "misread", "outread", "primate", "primates", "proofread", "putting",
    "ragged", "read",
    "reread", "row", "rowed", "rows", "rowing", "secreted", "secreting",
    "shower", "showers", "sightread", "slough", "sloughed", "sloughier",
    "sloughiest", "sloughiness", "sloughs", "sloughy", "sounds", "tear",
    "tearing", "tears", "thinks", "unbowed", "unbowing", "uncleanly", "wants",
    "wicked", "wind", "winding", "winds", "wound",
}


def _normalize_apostrophes(word):
    return word.replace("’", "'").replace("ʼ", "'")


def _load_csv(path, target, key_transform=lambda k: k):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        reader = csv.reader(fh)
        first = True
        for row in reader:
            if len(row) < 4:
                continue
            word, pos, enc, eusp = row[0], row[1], row[2], row[3]
            if first and not enc.isdigit():
                first = False
                continue  # header
            first = False
            if not enc.isdigit():
                continue
            spellings = [] if eusp in ("", "[]") else eusp.split("|")
            target[key_transform(word)] = {
                "pos": pos.split("|"),
                "encoding": int(enc),
                "spellings": spellings,
            }


def _load():
    if _LEXICON:
        return
    _load_csv(os.path.join(_DATA, "lexicon.csv"), _LEXICON)
    _load_csv(os.path.join(_DATA, "abbreviations.csv"), _ABBR)
    _load_csv(
        os.path.join(_DATA, "contractions.csv"),
        _CONTRACTIONS,
        key_transform=lambda k: _normalize_apostrophes(k).lower(),
    )
    with open(os.path.join(_DATA, "vvz_svm.tsv"), "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            feat, _, weight = line.partition("\t")
            _SVM[feat] = float(weight)
    _build_reverse()


def _americanize(w):
    """Reduce a British spelling to its American form across the common variant
    classes. Only ever consulted between two sources of the same euspell form (or
    a source and a standard headword), so it can't mis-fire on an unrelated word
    even where a rule is broad (re$ -> er also rewrites "acre")."""
    w = re.sub(r"our(s?)$", r"or\1", w)                                     # colour -> color
    w = re.sub(r"isation(s?)$", r"ization\1", w)                           # organisation -> organization
    w = re.sub(r"ise(s|d)?$", lambda m: "ize" + (m.group(1) or ""), w)     # organise(s|d) -> organize
    w = re.sub(r"ising$", "izing", w)
    w = re.sub(r"yse(s|d)?$", lambda m: "yze" + (m.group(1) or ""), w)     # analyse -> analyze
    w = re.sub(r"ysing$", "yzing", w)
    w = re.sub(r"ence(s?)$", r"ense\1", w)                                 # defence -> defense
    w = re.sub(r"re$", "er", w)                                            # centre -> center, metre -> meter
    w = re.sub(r"ogue(s?)$", r"og\1", w)                                   # catalogue -> catalog
    w = re.sub(r"gramme(s?)$", r"gram\1", w)                               # programme -> program
    w = re.sub(r"dgement(s?)$", r"dgment\1", w)                            # judgement -> judgment
    return w


def _more_american(a, b):
    """Prefer the American spelling, matching the forward British->American
    normalization: two sources of one euspell form that reduce to the same
    American spelling -> keep whichever is already American. Non-variant pairs
    (night/nite) reduce differently, so the first-seen source is kept."""
    if a == b:
        return False
    am_a, am_b = _americanize(a), _americanize(b)
    return am_a == am_b and a == am_a


def _build_reverse():
    """euspell reformed form -> traditional word. A reform that coincides with a
    real word (ruff, dorr, putz) is still reverted; a British->American
    normalization (encoding 601) whose target is a standard word, or a form that
    maps to itself (colors), is left as-is. Among variant sources the American
    spelling wins. Contraction clitics ('z -> 's) included."""
    for key, entry in _LEXICON.items():
        for e in entry["spellings"]:
            if e == key:
                continue
            if e in _LEXICON:
                if entry["encoding"] == 601:
                    continue
                if e in _LEXICON[e]["spellings"]:
                    continue
                if _americanize(key) == e:  # key is British-longer of e (judgement->judgment)
                    continue
            if e not in _REVERSE or _more_american(key, _REVERSE[e]):
                _REVERSE[e] = key
    for key, entry in _CONTRACTIONS.items():
        for e in entry["spellings"]:
            if e != key and e not in _REVERSE:
                _REVERSE[e] = key


# --- contractions -----------------------------------------------------------

def _get_contraction(word):
    return _CONTRACTIONS.get(_normalize_apostrophes(word).lower())


def _is_contraction(word):
    return _normalize_apostrophes(word).lower() in _CONTRACTIONS


def _contraction_components(word):
    entry = _get_contraction(word)
    if not entry:
        return []
    seqs = [a.strip().split() for a in entry["pos"]]
    seqs = [s for s in seqs]
    width = max((len(s) for s in seqs), default=0)
    positions = [list() for _ in range(width)]
    for seq in seqs:
        for i, tag in enumerate(seq):
            if tag not in positions[i]:
                positions[i].append(tag)
    return ["|".join(p) for p in positions]


# --- tagger -----------------------------------------------------------------

def tag_word(word):
    key = word.lower()
    entry = _LEXICON.get(key) or _ABBR.get(key) or _get_contraction(word)
    if entry:
        return "|".join(entry["pos"])
    if re.match(r"^\d", key):
        return "MC"
    return ""


# --- tokenizer --------------------------------------------------------------

_RUN = re.compile(r"['’ʼ]?\w+(?:['’ʼ]\w+)*['’ʼ]?")
_GENITIVE = re.compile(r"^(\w+)(['’ʼ]s)$", re.IGNORECASE)
_SENTENCE_BREAK = re.compile(r"[.!?]")
_LEAD_APOS = re.compile(r"^['’ʼ]+")
_TRAIL_APOS = re.compile(r"['’ʼ]+$")


def _classify_run(run):
    """Yield (kind, text) segments for one RUN match."""
    if _is_contraction(run):
        yield ("contraction", run)
        return
    gen = _GENITIVE.match(run)
    if gen and _is_contraction("'s"):
        yield ("word", gen.group(1))
        yield ("contraction", gen.group(2))
        return
    lead_m = _LEAD_APOS.match(run)
    lead = lead_m.group(0) if lead_m else ""
    rest = run[len(lead):]
    trail_m = _TRAIL_APOS.search(rest)
    trail = trail_m.group(0) if trail_m else ""
    core = rest[: len(rest) - len(trail)]
    if lead:
        yield ("sep", lead)
    if core:
        yield ("word", core)
    if trail:
        yield ("sep", trail)


def _tokenize(text):
    last = 0
    for m in _RUN.finditer(text):
        if m.start() > last:
            yield ("sep", text[last:m.start()])
        for seg in _classify_run(m.group(0)):
            yield seg
        last = m.end()
    if last < len(text):
        yield ("sep", text[last:])


# --- context window ---------------------------------------------------------

_BOUNDARY = {"word": "", "tag": "ZB", "breakAfter": True}


def _crosses_sentence_break(tokens, frm, to):
    lo, hi = (frm, to) if frm < to else (to, frm)
    for k in range(lo, hi):
        if tokens[k]["breakAfter"]:
            return True
    return False


def _context_window(tokens, idx):
    def at(i):
        if i < 0 or i >= len(tokens) or _crosses_sentence_break(tokens, idx, i):
            return _BOUNDARY
        return tokens[i]
    return [at(idx - 3), at(idx - 2), at(idx - 1), tokens[idx],
            at(idx + 1), at(idx + 2), at(idx + 3)]


def _tags_of(token):
    return token["tag"].split("|") if token["tag"] else []


def _any_prefix(token, prefixes):
    return any(any(t.startswith(p) for p in prefixes) for t in _tags_of(token))


def _any_prefix_real(token, prefixes):
    """_any_prefix ignoring ditto tags — for a test that CATEGORICALLY decides
    the answer rather than contributing a vote. In a vote a ditto tag only
    inflates a magnitude, but in a branch that returns, one spurious match flips
    the answer: "a" carries NN132, so it counted as the noun in _is_verbal_s's
    attributive test. Mirrors anyPrefixReal in pos.js."""
    return any(
        not re.search(r"\d\d$", t) and any(t.startswith(p) for p in prefixes)
        for t in _tags_of(token)
    )


def _any_exact(token, tags):
    return any(t in tags for t in _tags_of(token))


# --- tag-class constants (mirror pos.js) ------------------------------------

_DETERMINER = ["AT", "AT1", "DD", "DD1", "DD2", "DA", "DA1", "DA2", "DAR", "DAT", "DB", "DB2"]
_PREMODIFIER = ["APPGE", "JJ", "MC", "MD", "MF"]
_PREPOSITION = ["II", "IO", "IF", "IW"]
_SUBJECT_3SG = ["PPHS1", "PPH1"]
_REL_SUBJECT = ["PNQS", "DDQ", "CST"]
_VERB_ANY = ["VV", "VB", "VH", "VD", "VM"]
_PLURAL_VERB = ["VV0", "VBR", "VBDR", "VH0", "VD0"]
_OBJECT_PRONOUN = ["PPHO", "PPIO", "PPX", "PPH1", "PPY"]
_SINGULAR_NOUN = ["NN1", "NNU1", "NNL1", "NNT1", "NNO1", "NNB", "NP1"]
_ADVERB = ["RR", "RG", "RP", "RL", "RT", "RA"]
_SUBJECT_PRON = ["PPHS1", "PPH1", "PPHS2", "PPIS1", "PPIS2", "PPY"]
_VV0_SUBJECT_PRON = ["PPIS1", "PPIS2", "PPHS2", "PPY"]
_DEGREE_ADVERB = ["RG", "RGR", "RGT", "RGQ"]
_PLURAL_DET = ["DD2", "DA2", "DB2"]
_CARDINAL = ["MC", "MC2"]
_SINGULAR_DET = ["AT1", "DD1", "MC1", "DA1"]
_PLURAL_AGREE = ["VBR", "VBDR", "VH0", "VD0"]
_SINGULAR_AGREE = ["VBZ", "VBDZ", "VHZ", "VDZ", "VVZ"]


def _is_pure_adverb(token):
    tags = _tags_of(token)
    return len(tags) > 0 and all(any(t.startswith(p) for p in _ADVERB) for t in tags)


def _vvz_score(tokens, idx):
    """Signed hand-rule context vote for the NN2|VVZ decision (> 0 => VVZ).
    Mirrors vvzScore in pos.js; its negative (noun) votes veto weak SVM verb
    calls in _is_vvz_svm."""
    win = _context_window(tokens, idx)
    w3b, w2b, w1b, w1a, w2a = win[0], win[1], win[2], win[4], win[5]
    before_adv = _is_pure_adverb(w1b)
    left = w2b if before_adv else w1b
    left_back = w3b if before_adv else w2b
    vote = 0

    # BEFORE: an unambiguous subject argues for the verb.
    if _any_exact(left, _SUBJECT_3SG):
        vote += 3                                      # "it records"
    elif _any_prefix(left, _REL_SUBJECT):
        vote += 2                                      # "device which records"
    elif _any_prefix(left, ["NP"]):
        vote += 2                                      # "John records"

    # Noun-phrase context before -> the plural-noun reading (the default).
    if _any_exact(left, _DETERMINER) or _any_prefix(left, _PREMODIFIER):
        vote -= 3                                      # "the/old/two tools"
    if _any_prefix(left, _PREPOSITION):
        vote -= 3                                      # "of tools"
    if _any_prefix(left, ["NN"]):
        vote -= 2                                      # "learning tools"
    if _any_exact(left, ["VM", "TO"]):
        vote -= 3                                      # "will/to tool(s)"
    elif _any_prefix(left, _VERB_ANY) and not _any_exact(left, _SUBJECT_3SG):
        vote -= 1                                      # "plays records"

    # AFTER: a complement only a finite verb takes argues for the verb.
    after_verb = w2a if _is_pure_adverb(w1a) else w1a
    if _any_exact(after_verb, _PLURAL_VERB):
        vote -= 3                                      # "records show"
    elif _any_exact(after_verb, ["VVD"]) and not _any_prefix(after_verb, ["NN"]):
        vote -= 3                                      # "the phone calls stopped"
    if _any_prefix(w1a, _OBJECT_PRONOUN):
        vote += 3                                      # "records them"
    if _any_exact(w1a, _DETERMINER) or _any_prefix(w1a, ["APPGE"]):
        vote += 2                                      # "records the / his X"
    if _any_prefix(w1a, ["NP"]):
        vote += 2                                      # "meets Mary"
    if _any_prefix(w1a, ["RR"]):
        vote += 1                                      # "functions well"

    # A clear subject NP + target + verb complement -> a finite verb.
    det_subject = _any_exact(left_back, _DETERMINER) or (
        not before_adv and _any_prefix(w2b, ["JJ", "MC", "MD", "MF"]) and _any_exact(w3b, _DETERMINER))
    subject_noun = _any_prefix(left, ["NP"]) or (_any_exact(left, _SINGULAR_NOUN) and det_subject)
    verb_complement = (_any_prefix(w1a, _OBJECT_PRONOUN) or _any_exact(w1a, _DETERMINER)
                       or _any_prefix(w1a, ["APPGE", "RR", "RP", "NP"]))
    if subject_noun and verb_complement:
        vote += 3

    return vote


# --- NN2|VVZ SVM ------------------------------------------------------------

# CLAWS7 ditto tags (II22, JJ21, NN132, ...) mark "word k of an n-word multiword
# expression"; as candidate readings of an isolated word they are noise, so they
# map to no family (mirrors pos.js svmFamily).
_DITTO = re.compile(r"\d\d$")


def _svm_family(tag):
    if _DITTO.search(tag):
        return None
    if tag.startswith("NP"):
        return "NP"
    if tag.startswith("NN"):
        return "NN"
    if tag in ("PPHS1", "PPH1"):
        return "SUBJ3SG"
    if tag.startswith("PPHO") or tag.startswith("PPIO") or tag.startswith("PPX") or tag.startswith("PPY"):
        return "OBJPRON"
    if tag in ("AT", "AT1") or tag.startswith("DD") or tag.startswith("DA") or tag.startswith("DB"):
        return "DET"
    if tag.startswith("APPGE"):
        return "POSS"
    if tag.startswith("II") or tag.startswith("IO") or tag.startswith("IF") or tag.startswith("IW"):
        return "PREP"
    if tag.startswith("JJ") or tag.startswith("MC") or tag.startswith("MD") or tag.startswith("MF"):
        return "PREMOD"
    if tag in ("VV0", "VBR", "VBDR", "VH0", "VD0"):
        return "PLVERB"
    if tag == "VVD":
        return "VPAST"
    if tag.startswith("VV") or tag.startswith("VB") or tag.startswith("VH") or tag.startswith("VD") or tag.startswith("VM"):
        return "VERB"
    if tag.startswith("RR") or tag.startswith("RG") or tag.startswith("RP") or tag.startswith("RL") or tag.startswith("RT") or tag.startswith("RA"):
        return "ADV"
    if tag in ("PNQS", "DDQ", "CST"):
        return "RELSUBJ"
    return tag[:2]


_SVM_SLOTS = [(0, -3), (1, -2), (2, -1), (4, 1), (5, 2), (6, 3)]

# Closed-class candidate tags (preposition/conjunction/infinitival to) that
# lexicalize an adjacent neighbor -- see _svm_features.
_CLOSED_CLASS = ("II", "IO", "IF", "IW", "CC", "CS", "TO")


def _slot_fams(tok):
    """Family set for one context token, UNK for an unknown word (or one whose
    every reading is a ditto tag), or None for a boundary slot."""
    if tok["tag"] == "ZB":
        return None
    if tok["tag"] == "":
        return {"UNK"}
    fams = set()
    for t in tok["tag"].split("|"):
        f = _svm_family(t)
        if f is not None:
            fams.add(f)
    return fams if fams else {"UNK"}


def _svm_features(tokens, idx):
    # Mirrors svmFeatures in pos.js: per-slot non-ditto families, an adjacent
    # (+/-1) closed-class word's identity ("1w=of"), and the (-2,-1) family
    # pair ("p=DET~NN"). Boundary slots fire nothing.
    win = _context_window(tokens, idx)
    word = tokens[idx]["word"] if idx < len(tokens) else ""
    feats = ["bias", "w=" + word.lower()]
    if word[:1].isupper():
        feats.append("cap")
    per_off = {}
    for slot, off in _SVM_SLOTS:
        tok = win[slot]
        fams = _slot_fams(tok)
        per_off[off] = fams
        if off in (-1, 1) and tok["tag"] not in ("ZB", ""):
            if any(t.startswith(_CLOSED_CLASS) and not _DITTO.search(t)
                   for t in tok["tag"].split("|")):
                feats.append(str(off) + "w=" + tok["word"].lower())
        if fams is None:
            continue
        for f in fams:
            feats.append(str(off) + "=" + f)
    if per_off.get(-2) and per_off.get(-1):
        for fa in per_off[-2]:
            for fb in per_off[-1]:
                feats.append("p=" + fa + "~" + fb)
    return feats


# How much one hand-rule vote point counts against the SVM score (mirrors
# RULE_VETO in pos.js): the rule's categorical noun evidence can veto a weak
# learned verb call ("the call records between ..." stays a noun).
_RULE_VETO = 0.16


def _is_vvz_svm(tokens, idx):
    score = 0.0
    for f in _svm_features(tokens, idx):
        score += _SVM.get(f, 0.0)
    return score + _RULE_VETO * min(0, _vvz_score(tokens, idx)) > 0


# --- POS predicates ---------------------------------------------------------

def _is_verbal_s(tokens, idx):
    win = _context_window(tokens, idx)
    w1b, w1a, w2a = win[2], win[4], win[5]
    if _any_exact(w1b, _SUBJECT_PRON):
        return True
    # Ditto-aware: both tests return, so one spurious match flips the answer.
    if _any_prefix_real(w1a, ["VVN", "VVG"]):
        return not _any_prefix_real(w2a, ["NN", "NP"])
    return False


def _vv0_score(tokens, idx):
    """Signed hand-rule context vote for the POS-heteronym decision (> 0 => VV0).

    Only a word that can EXCLUSIVELY be an adverb is looked through, exactly as
    _vvz_score does: the tagger reports a full candidate set, and determiners
    carry stray ditto-adverb tags ("the" is AT|...|RG42|RR22|RT42), so a loose
    prefix test skipped them and discarded the decisive noun cue.
    """
    win = _context_window(tokens, idx)
    w2b, w1b, w1a = win[1], win[2], win[4]
    left = w2b if _is_pure_adverb(w1b) else w1b
    vote = 0
    if _any_exact(left, ["TO"]):
        vote += 4
    if _any_prefix(left, ["VM"]):
        vote += 4
    if _any_prefix(left, ["VD"]):
        vote += 3
    if _any_exact(left, _VV0_SUBJECT_PRON):
        vote += 3
    if _any_prefix(left, _REL_SUBJECT):
        vote += 2
    if _any_exact(left, _DETERMINER):
        vote -= 4
    if _any_prefix(left, ["APPGE"]):
        vote -= 4
    if _any_prefix(left, ["VB"]):
        vote -= 3
    if _any_prefix(left, _PREPOSITION):
        vote -= 3
    if _any_prefix(left, ["MC", "MD", "MF"]):
        vote -= 2
    if _any_exact(w1b, _DEGREE_ADVERB):
        vote -= 3
    if _any_exact(w1a, _DETERMINER) or _any_prefix(w1a, ["APPGE"]):
        vote += 2
    if _any_prefix(w1a, _OBJECT_PRONOUN):
        vote += 2
    return vote


def _is_verb_vv0(tokens, idx):
    """Threshold _vv0_score; on a ZERO vote defer to the word's own base rate.

    The context vote carries no per-word bias, so its single noun-first default
    was wrong for verb-dominant words ("live" is ~87% verb). A word in
    _VV0_VERB_DEFAULT takes the verb reading when context is silent; context
    still wins wherever it has an opinion. Mirrors is_verb_VV0 in pos.js.
    """
    vote = _vv0_score(tokens, idx)
    if vote != 0:
        return vote > 0
    return (tokens[idx].get("word") or "").lower() in _VV0_VERB_DEFAULT


def _is_plural_noun(tokens, idx):
    win = _context_window(tokens, idx)
    w2b, w1b, w1a = win[1], win[2], win[4]
    vote = 0
    if _any_exact(w1b, _PLURAL_DET) or _any_exact(w1b, _CARDINAL):
        vote += 3
    if _any_exact(w1b, _SINGULAR_DET):
        vote -= 3
    if _any_prefix(w1b, ["JJ"]):
        if _any_exact(w2b, _PLURAL_DET) or _any_exact(w2b, _CARDINAL):
            vote += 2
        if _any_exact(w2b, _SINGULAR_DET):
            vote -= 2
    if _any_exact(w1a, _PLURAL_AGREE):
        vote += 3
    if _any_exact(w1a, _SINGULAR_AGREE):
        vote -= 3
    return vote > 0


# --- conversion -------------------------------------------------------------

def _is_sentence_start(tokens, idx):
    return idx == 0 or (idx > 0 and tokens[idx - 1]["breakAfter"])


def _match_case(original, replacement):
    if original == original.upper():
        return replacement.upper()
    if original[:1] == original[:1].upper():
        return replacement[:1].upper() + replacement[1:]
    return replacement


def _route(key, entry, tokens, idx):
    """Spelling index for a multi-spelling entry. Mirrors converter.route() for
    the POS-decided diatones. A semantic (encoding-202 / 3-4-way) word returns
    None: its choice needs a per-word rule not ported in v1, so auto-conversion
    leaves it unchanged and the callers offer its spellings as choices instead."""
    pos = entry["pos"]
    enc = entry["encoding"]
    if (enc == 12 or enc == 112) and "VVZ" in pos and key not in _SEMANTIC_WORDS:
        return 1 if _is_vvz_svm(tokens, idx) else 0
    if "GE" in pos:
        return 1 if _is_verbal_s(tokens, idx) else 0
    if enc == 702 and "NN2" in pos:
        return 1 if _is_plural_noun(tokens, idx) else 0
    # 102 = the "-ate" stress pairs; 152 = the non-"-ate" heteronyms (use, house,
    # live, ...). Same verb-vs-noun question, so one decision (see converter.js).
    if enc in (102, 152) and "VV0" in pos and key not in _SEMANTIC_WORDS:
        return 1 if _is_verb_vv0(tokens, idx) else 0
    if key in _SEMANTIC_WORDS:
        return None  # left to the user via word_candidates()
    return 0  # non-semantic, undecidable -> lexicon default (matches JS)


def _convert(word, tokens, idx):
    if word == "I":
        return "Ih" if _is_sentence_start(tokens, idx) else "ih"
    key = word.lower()
    if key in _KEEP_UNCHANGED:
        return word
    entry = _LEXICON.get(key) or _get_contraction(word)
    if not entry:
        return word
    variants = entry["encoding"] % 10
    if variants == 0:
        return word
    spellings = entry["spellings"]
    if variants == 1:
        return _match_case(word, spellings[0] if spellings else word)
    sp_idx = _route(key, entry, tokens, idx)
    if sp_idx is None:
        return word  # semantic homograph: leave for the user to pick
    repl = spellings[sp_idx] if 0 <= sp_idx < len(spellings) else word
    return _match_case(word, repl)


def _build_tokens(text):
    """Tokenize `text` into (pieces, tokens) where pieces reassemble to the
    output and tokens are the tagged stream (with contraction pseudo-tokens).
    Mirrors dom-walker.convertBlock minus phrase collapsing."""
    pieces = []   # {'text': str, 'wordIdx': int}
    tokens = []   # {'word','tag','breakAfter'}
    for kind, seg in _tokenize(text):
        if kind == "sep":
            pieces.append({"text": seg, "wordIdx": -1})
            if tokens and _SENTENCE_BREAK.search(seg):
                tokens[-1]["breakAfter"] = True
        elif kind == "contraction":
            piece_idx = len(pieces)
            pieces.append({"text": seg, "wordIdx": len(tokens)})
            components = _contraction_components(seg)
            if components:
                for i, tag in enumerate(components):
                    tokens.append({"word": seg if i == 0 else "", "tag": tag, "breakAfter": False})
            else:
                tokens.append({"word": seg, "tag": tag_word(seg), "breakAfter": False})
        else:  # word
            pieces.append({"text": seg, "wordIdx": len(tokens)})
            tokens.append({"word": seg, "tag": tag_word(seg), "breakAfter": False})
    if tokens:
        tokens[-1]["breakAfter"] = True
    return pieces, tokens


# --- public API -------------------------------------------------------------

def convert_text(text):
    """Convert a run of text (a paragraph/sentence) to euspell."""
    _load()
    pieces, tokens = _build_tokens(text)
    out = []
    for p in pieces:
        if p["wordIdx"] != -1:
            out.append(_convert(p["text"], tokens, p["wordIdx"]))
        else:
            out.append(p["text"])
    return "".join(out)


_CLITIC = re.compile(r"^(.+)(['’ʼ][zs])$")


def _revert_word(w):
    if w.lower() == "ih":
        return "I"  # pronoun ih/Ih -> I
    t = _REVERSE.get(w.lower())
    if t:
        return _match_case(w, t)
    m = _CLITIC.match(w)  # "he'z" -> "he" + "'s"
    if m:
        st = _REVERSE.get(m.group(1).lower())
        stem = _match_case(m.group(1), st) if st else m.group(1)
        cl = _REVERSE.get(_normalize_apostrophes(m.group(2)).lower())
        return stem + (cl if cl is not None else m.group(2))
    return w


def revert_text(text):
    """Convert euspell text back to traditional English (the inverse of
    convert_text). Word-level lexicon lookup, no context needed."""
    _load()
    out = []
    for kind, seg in _tokenize(text):
        out.append(seg if kind == "sep" else _revert_word(seg))
    return "".join(out)


def proofread(text):
    """Context-aware markup for a run of text. Returns a list of
    {start, length, word, suggestions} — one per word that should be reformed,
    with character offsets into `text`. For a confidently decided word the first
    suggestion is the chosen euspelling (any alternates follow); for a semantic
    homograph (left unchanged by convert_text) the euspell choices are offered,
    the changed spelling first. Words already in their euspell form, or with no
    reform, produce no entry. Used by the proofreader UNO component."""
    _load()
    pieces, tokens = _build_tokens(text)
    out = []
    offset = 0
    for p in pieces:
        seg = p["text"]
        if p["wordIdx"] != -1:
            decided = _convert(seg, tokens, p["wordIdx"])
            cands = word_candidates(seg)
            suggestions = None
            if decided != seg:
                suggestions = [decided] + [c for c in cands if c != decided]
            elif seg.lower() in _SEMANTIC_WORDS and cands:
                diff = [c for c in cands if c.lower() != seg.lower()]
                same = [c for c in cands if c.lower() == seg.lower()]
                suggestions = diff + same
            if suggestions:
                out.append({"start": offset, "length": len(seg),
                            "word": seg, "suggestions": suggestions})
        offset += len(seg)
    return out


def word_candidates(word):
    """Context-free euspell spellings for a single word, best-guess first, or []
    if the word is unchanged/unknown. Used by the spell checker (no context) and
    by the proofreader to offer choices for semantic homographs."""
    _load()
    if word == "I":
        return ["ih"]
    key = word.lower()
    if key in _KEEP_UNCHANGED:
        return []
    entry = _LEXICON.get(key) or _get_contraction(word)
    if not entry:
        return []
    if entry["encoding"] % 10 == 0:
        return []
    seen = []
    for sp in entry["spellings"]:
        cased = _match_case(word, sp)
        if cased not in seen:
            seen.append(cased)
    return seen


def is_known_euspelling(word):
    """True if `word` is itself a euspell output spelling (so a spell checker
    treats already-converted text as valid)."""
    _load()
    return word.lower() in _EUSPELLINGS


# Set of every euspell output spelling, for is_known_euspelling().
_EUSPELLINGS = set()


def _index_euspellings():
    if _EUSPELLINGS:
        return
    _load()
    for entry in _LEXICON.values():
        for sp in entry["spellings"]:
            _EUSPELLINGS.add(sp.lower())


if __name__ == "__main__":
    import sys
    _load()
    _index_euspellings()
    for line in sys.stdin:
        sys.stdout.write(convert_text(line.rstrip("\n")) + "\n")
