// GENERATED by build/gen-vv0-prior.mjs — do not edit.
//
// Words whose POS-heteronym decision defaults to the VERB reading when the
// context vote is exactly zero (see is_verb_VV0 in pos.js). Every other word —
// and every case where context has any opinion at all — keeps the global
// noun-first default.
//
// Learned from the CLAWS-tagged corpus on the training four-fifths, and listed
// only where the verb default beats the noun default on that split. See the
// generator's header for why the prior is applied only on a zero vote rather
// than as a bias added to the vote.
//
// encoding 152 | 4 of 15 words
// held-out accuracy: rule 91.3% -> with default 94.3%
export const VV0_VERB_DEFAULT = new Set([
  "bear",
  "live",
  "mow",
  "reuse",
]);
